# .bash_profile
#

# Source any local settings
if [[ -e "${HOME}/.bash_profile_local" ]]; then
    source "${HOME}/.bash_profile_local"
fi


#### Env config
# add ~/bin to PATH
if [[ ! -d "${HOME}/bin" ]]; then
    mkdir "${HOME}/bin"
fi
export PATH=$PATH:~/bin


#### Aliases
# workaround failed ssh known hosts
alias sshi="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
# sublime
if [[ -e "/Applications/Sublime Text.app" ]]; then
    alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
fi

# custom ls
alias ls="ls -laG"

# launch screen saver
alias ss="/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"


#### GO lang stuff
if [[ -d /usr/local/go ]]; then
    export GOPATH="$HOME/Documents/_Dev/golang"
    export PATH=$GOPATH/bin:$PATH
fi

#### Python virtualenvwrapper
if [[ -e /usr/local/bin/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/Documents/_Dev/
    source /usr/local/bin/virtualenvwrapper.sh
fi
